version: '3.8'

services:
  mysql:
    container_name: lms-db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./db/lms.sql:/docker-entrypoint-initdb.d/lms.sql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: lms
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  app:
    container_name: lms
    image: python:3.9-slim
    ports:
      - "5000:5000"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DB: lms
    depends_on:
      - mysql

volumes:
  db-data:
